---
title: Jeremiah Baarbe
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  travel:
    title: Travel
    output: true
    permalink: "/travel/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: travel
  values:
    layout: single
    author_profile: true
    read_time: true
    share: true
    related: true
    subtitle: Hello world
locale: en
title_separator: "―"
name: Jeremiah Baarbe
description: Law student interested in tech and law. Searching for articling positions
  for Summer, 2018
url: http://baarbe.ca
baseurl: 
repository: 
teaser: "/assets/img/Madrid Sun.jpg"
breadcrumbs: false
words_per_minute: 200
atom_feed:
  path: 
google_site_verification: 
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
twitter:
  username: "@baarbeh"
facebook:
  username: 
  app_id: 
  publisher: 
  og_image: http://baarbe.ca/assets/img/baarbe-og.jpg
social:
  type: 
  name: Jeremiah Baarbe
  links: 
analytics:
  provider: "google"
  google:
    tracking_id: "UA-92975012-1"
author:
  name: Jeremiah Baarbe
  avatar: http://baarbe.ca/assets/img/baarbe.jpg
  bio: Building tech to answer challenging legal questions
  location: Ottawa, ON
  email: 
  uri: 
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: 
  foursquare: 
  github: "/baarbeh/"
  google_plus: 
  keybase: 
  instagram: 
  lastfm: 
  linkedin: "/jeremiahbaarbe/"
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: "/@baarbeh/"
  vine: 
  weibo: 
  xing: 
  youtube: 
include:
- ".htaccess"
- _pages
- _travel
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- "/docs"
- "/test"
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
